// Поисковые запросы к фотостоку для каждого рецепта (англ. — так стоки ищут лучше)
export const Q = {
"Борщ украинский":"borscht soup bowl","Щи из квашеной капусты":"cabbage soup bowl","Солянка мясная":"meat solyanka soup","Уха речная":"fish soup bowl","Куриная лапша":"chicken noodle soup","Гороховый суп с копчёностями":"pea soup smoked","Окрошка на квасе":"cold summer soup okroshka","Грибной крем-суп":"mushroom cream soup","Харчо":"georgian beef soup kharcho","Том ям с креветками":"tom yum shrimp soup","Минестроне":"minestrone soup","Крем-суп из тыквы":"pumpkin soup bowl",
"Оливье":"olivier potato salad","Салат «Шуба»":"herring beetroot layered salad","Греческий салат":"greek salad feta","Цезарь с курицей":"caesar salad chicken","Винегрет":"beetroot vinegret salad","Табуле":"tabbouleh parsley salad","Салат с тунцом и фасолью":"tuna bean salad","Капрезе":"caprese salad mozzarella","Салат с киноа и авокадо":"quinoa avocado salad","Тёплый салат с говядиной":"warm beef salad","Морковь по-корейски":"spicy carrot salad",
"Котлеты по-киевски":"chicken kiev cutlet","Бефстроганов":"beef stroganoff","Плов узбекский":"uzbek plov rice lamb","Голубцы":"cabbage rolls tomato sauce","Пельмени домашние":"pelmeni dumplings","Курица по-грузински чкмерули":"chicken garlic cream sauce pan","Стейк рибай":"ribeye steak","Паста карбонара":"carbonara pasta","Лазанья болоньезе":"lasagna bolognese","Ризотто с грибами":"mushroom risotto","Рыба, запечённая целиком":"whole baked fish lemon","Гуляш по-венгерски":"hungarian goulash","Тефтели в томатном соусе":"meatballs tomato sauce","Курица терияки":"teriyaki chicken sesame","Свинина в кисло-сладком соусе":"sweet and sour pork","Овощное рагу":"vegetable stew ratatouille","Котлеты из индейки":"turkey cutlets plate","Запечённая свиная рулька":"roasted pork knuckle","Драники":"potato pancakes sour cream","Форель на гриле":"grilled trout fillet","Курица карри":"chicken curry coconut","Паста с песто":"pesto pasta basil","Рыбные котлеты":"fish cakes plate","Запечённые овощи с фетой":"roasted vegetables feta tray","Бургер домашний":"homemade burger cheddar","Шаурма домашняя":"shawarma wrap",
"Шакшука":"shakshuka eggs tomato","Сырники":"syrniki cheese pancakes","Овсяная каша с грушей":"oatmeal porridge pear","Блины тонкие":"thin crepes blini","Омлет французский":"french omelette","Гранола домашняя":"granola bowl","Авокадо-тост":"avocado toast egg","Оладьи на кефире":"fluffy pancakes stack","Яйца бенедикт":"eggs benedict hollandaise","Каша гречневая с грибами":"buckwheat mushrooms plate",
"Хлеб на закваске":"sourdough bread loaf","Пирожки с капустой":"baked cabbage buns pirozhki","Шарлотка с яблоками":"apple sponge cake","Наполеон":"napoleon mille feuille cake","Медовик":"honey layer cake","Чизкейк Нью-Йорк":"new york cheesecake","Круассаны":"croissants","Фокачча с розмарином":"rosemary focaccia","Хачапури по-аджарски":"adjarian khachapuri","Кулич пасхальный":"easter bread kulich","Булочки с корицей":"cinnamon rolls","Пицца маргарита":"margherita pizza","Кекс лимонный":"lemon loaf cake","Печенье с шоколадом":"chocolate chip cookies",
"Тирамису":"tiramisu dessert","Панна котта":"panna cotta berries","Крем-брюле":"creme brulee","Шоколадный фондан":"chocolate lava cake","Пахлава":"baklava","Эклеры":"eclairs pastry","Мороженое пломбир":"vanilla ice cream scoops","Яблочный штрудель":"apple strudel","Чак-чак":"chak chak honey dessert","Творожная запеканка":"cottage cheese casserole","Ягодный крамбл":"berry crumble","Мусс из тёмного шоколада":"chocolate mousse glass",
"Хумус":"hummus bowl olive oil","Баклажанная икра":"eggplant spread bowl","Селёдка под маринадом":"marinated herring onion","Брускетта с томатами":"tomato bruschetta","Рулетики из баклажанов":"eggplant rolls cheese","Фаршированные яйца":"deviled eggs","Тарталетки с креветками":"shrimp tartlets canape","Куриные крылышки баффало":"buffalo chicken wings","Сырная тарелка":"cheese board platter","Лобио":"red bean lobio walnuts","Маринованные грибы":"marinated mushrooms jar","Паштет из куриной печени":"chicken liver pate",
"Компот из сухофруктов":"dried fruit compote drink","Морс клюквенный":"cranberry drink glass","Глинтвейн":"mulled wine spices","Лимонад имбирный":"ginger lemonade glass","Какао на молоке":"hot cocoa marshmallow","Раф кофе":"latte coffee cup foam"
};
